on:
  workflow_call:
    inputs:
      compare-versions:
        required: false
        type: boolean
        default: true
    outputs:
      current-galaxy-version-chain:
        description: "Current chain collection Galaxy version"
        value: ${{ jobs.check-version.outputs.current-galaxy-version-chain }}
      current-galaxy-version-common:
        description: "Current common collection Galaxy version"
        value: ${{ jobs.check-version.outputs.current-galaxy-version-common }}
jobs:
  check-version:
    runs-on: ubuntu-22.04
    outputs:
      current-galaxy-version-chain: ${{ steps.check-current-version.outputs.current-galaxy-version-chain }}
      current-galaxy-version-common: ${{ steps.check-current-version.outputs.current-galaxy-version-common }}
    steps:
      - name: Setup Python modules
        run: pip3 install --no-cache-dir yq
      - name: Checkout current ref
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Checkout main ref
        if: ${{ inputs.compare-versions }}
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: "main/${{ github.repository }}"
      - name: Check the current version
        id: check-current-version
        run: |
          ROLES=$(find $GITHUB_REPOSITORY -maxdepth 1 -type d -name '[!.]*')
          for ROLE in $ROLES; do
            CURRENT_GALAXY_VERSION=$(cat ${GITHUB_REPOSITORY}/${ROLE}/galaxy.yml | yq -r '.version' | tr -d '\n')
            echo "Current ${ROLE} collection Galaxy version: ${CURRENT_GALAXY_VERSION}"
            if [ "$CURRENT_GALAXY_VERSION" != 'null' ]
            then
              echo "CURRENT_GALAXY_VERSION_${ROLE^^}=${CURRENT_GALAXY_VERSION}" >> "${GITHUB_ENV}"
              echo "current-galaxy-version-${ROLE,,}=${CURRENT_GALAXY_VERSION}" >> "${GITHUB_OUTPUT}"
            fi
          done
      - name: Check the versions in the main branch
        if: ${{ inputs.compare-versions }}
        run: |
          ROLES=$(find $GITHUB_REPOSITORY -maxdepth 1 -type d -name '[!.]*')
          for ROLE in $ROLES; do
            MAIN_GALAXY_VERSION=$(cat main/${GITHUB_REPOSITORY}/${ROLE}/galaxy.yml | yq -r '.version' | tr -d '\n')
            echo "Galaxy version of the ${ROLE} collection in the main branch: ${MAIN_GALAXY_VERSION}"
            echo "MAIN_GALAXY_VERSION_${ROLE^^}=${MAIN_GALAXY_VERSION}" >> "${GITHUB_ENV}"
          done
      - name: Validate the current version of the chain collection
        if: ${{ ! env.CURRENT_GALAXY_VERSION_CHAIN }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Your Galaxy version of the chain collection is absent or empty!')
      - name: Validate the current version of the common collection
        if: ${{ ! env.CURRENT_GALAXY_VERSION_COMMON }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Your Galaxy version of the common collection is absent or empty!')
      - name: Compare versions for the chain collection
        if: ${{ inputs.compare-versions && env.MAIN_GALAXY_VERSION_CHAIN >= env.CURRENT_GALAXY_VERSION_CHAIN }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Your Galaxy version of the chain collection is lower than the version in the main branch or equal. Please bump your version!')
      - name: Compare versions for the common collection
        if: ${{ inputs.compare-versions && env.MAIN_GALAXY_VERSION_COMMON >= env.CURRENT_GALAXY_VERSION_COMMON }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Your Galaxy version of the common collection is lower than the version in the main branch or equal. Please bump your version!')
